# Generated by Django 3.1.3 on 2021-11-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stores',
            fields=[
                ('StoresId', models.AutoField(primary_key=True, serialize=False)),
                ('StoresName', models.CharField(max_length=500)),
                ('Latitude', models.IntegerField()),
                ('Longitude', models.IntegerField()),
            ],
        ),
    ]
